import React,{useEffect,useState}from'react';
import{AlertTriangle,ArrowUpRight,BarChart3,BrainCircuit,ChevronRight,Database,IndianRupee,ShieldAlert,Sparkles,TrendingUp}from'lucide-react';
import{createRoot}from'react-dom/client';
import{BarChart,Bar,Cell,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import'./styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8001';
const fmt=n=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:1}).format(n);
const riskColor=b=>b==='High'?'high':b==='Medium'?'medium':'low';
function Card({icon:Icon,label,value,note,tone=''}){return <div className="metric-card"><div className={'icon '+tone}><Icon size={19}/></div><div><p className="eyebrow">{label}</p><p className="metric">{value}</p><p className="note">{note}</p></div></div>}
function Detail({data,onClose,onAsk}){let p=data.project;return <div className="overlay" onClick={onClose}><section className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><p className="eyebrow">PROJECT INTELLIGENCE · {p.project_id}</p><h2>{p.project_name}</h2><p className="subtitle">{p.sector} · {p.state} · ₹{fmt(p.approved_cost_crore)} Cr</p><div className="detail-kpis"><div><span>Risk score</span><b>{p.risk_score}/100</b></div><div><span>Cost overrun</span><b>{p.predicted_cost_overrun_pct}%</b></div><div><span>Time overrun</span><b>{p.predicted_time_overrun_pct}%</b></div></div><h3>Cost escalation drivers</h3>{data.drivers.map(d=><div className="driver" key={d.driver}><span>{d.driver}</span><div><i style={{width:`${Math.min(100,d.impact*4)}%`}}/></div><b>{d.impact}</b></div>)}<div className="peer"><p className="eyebrow">SECTOR BENCHMARK</p><b>{data.benchmark.project_vs_peer_risk>0?'+':''}{data.benchmark.project_vs_peer_risk} points vs sector average risk</b><p>Peer average: {data.benchmark.peer_avg_risk}/100</p></div><button className="copilot" onClick={onAsk}><BrainCircuit size={18}/> Ask PAIMANA AI for a recovery brief</button></section></div>}
function ProjectTable({items,onOpen}){return <div className="table"><table><thead><tr><th>Project</th><th>Risk</th><th>Cost model</th><th>Time model</th><th/></tr></thead><tbody>{items.map(p=><tr key={p.project_id} onClick={()=>onOpen(p.project_id)}><td><b>{p.project_name}</b><small>{p.project_id} · {p.sector}</small></td><td><em className={riskColor(p.risk_band)}>{p.risk_score} · {p.risk_band}</em></td><td>{p.predicted_cost_overrun_pct}%</td><td>{p.predicted_time_overrun_pct}%</td><td><ChevronRight size={17}/></td></tr>)}</tbody></table></div>}
function App(){
 const[data,setData]=useState(),[detail,setDetail]=useState(),[sector,setSector]=useState(''),[view,setView]=useState('portfolio'),[answer,setAnswer]=useState('');
 useEffect(()=>{fetch(`${API}/api/dashboard${sector?`?sector=${encodeURIComponent(sector)}`:''}`).then(r=>r.json()).then(setData)},[sector]);
 if(!data)return <main className="loading"><Sparkles/> Loading PAIMANA intelligence…</main>;
 const{kpis,risk_ranking:ranking,sector_benchmark:bench,alerts,filters}=data;
 const open=id=>fetch(`${API}/api/projects/${id}`).then(r=>r.json()).then(setDetail);
 const ask=id=>fetch(`${API}/api/assistant?project_id=${id}`).then(r=>r.json()).then(x=>{setAnswer(x.answer);setView('copilot')});
 const nav=[['portfolio','Portfolio command',BarChart3],['risk','Risk radar',ShieldAlert],['benchmark','Benchmarking',TrendingUp],['copilot','AI copilot',BrainCircuit]];
 return <div className="app"><aside><div className="brand"><i>P</i>PAIMANA <b>AI</b></div><p className="nav-label">INTELLIGENCE PLATFORM</p><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon/>{label}</button>)}</nav><div className="foot"><Database size={15}/>Synthetic demo data<br/><b>PAIMANA / CUF schema</b></div></aside><main><header><div><p className="eyebrow teal">GOVERNMENT PROJECT DELIVERY</p><h1>{view==='portfolio'?'Portfolio command centre':view==='risk'?'Risk radar':view==='benchmark'?'Benchmarking intelligence':'PAIMANA AI copilot'}</h1><p className="subtitle">{view==='portfolio'?'Anticipate overruns. Focus intervention where it matters.':view==='risk'?'Ranked early warnings for focused intervention.':view==='benchmark'?'Compare risk and forecast exposure across sectors.':'Ask for concise, evidence-based recovery guidance.'}</p></div><select value={sector} onChange={e=>setSector(e.target.value)}><option value="">All sectors</option>{filters.sectors.map(x=><option key={x}>{x}</option>)}</select></header><div className="notice"><Sparkles size={16}/>{data.data_notice}<span>Models trained on synthetic sample</span></div>
 {view==='portfolio'&&<><section className="metrics"><Card icon={BarChart3} label="Portfolio projects" value={kpis.projects} note="Active delivery portfolio"/><Card icon={ShieldAlert} label="High-risk projects" value={kpis.at_risk} note="Require executive attention" tone="rose"/><Card icon={TrendingUp} label="Average risk score" value={`${kpis.avg_risk}/100`} note="Model-based composite" tone="amber"/><Card icon={IndianRupee} label="Exposed budget" value={`₹${fmt(kpis.exposed_budget_crore)} Cr`} note="High-risk project value" tone="navy"/></section><section className="grid"><div className="panel wide"><div className="head"><div><p className="eyebrow">PRIORITY QUEUE</p><h2>Projects needing intervention</h2></div><button onClick={()=>setView('risk')}>View all <ArrowUpRight size={16}/></button></div><ProjectTable items={ranking} onOpen={open}/></div><AlertStream alerts={alerts}/><BenchmarkChart bench={bench}/><ModelCard/></section></>}
 {view==='risk'&&<section className="grid"><div className="panel wide"><div className="head"><div><p className="eyebrow">RISK RANKING</p><h2>Highest-priority delivery risks</h2></div><span className="eyebrow">CLICK A PROJECT FOR ANALYTICS</span></div><ProjectTable items={ranking} onOpen={open}/></div><AlertStream alerts={alerts}/></section>}
 {view==='benchmark'&&<section className="grid"><BenchmarkChart bench={bench}/><ModelCard/><div className="panel wide"><div className="head"><div><p className="eyebrow">SECTOR COMPARISON</p><h2>Forecasted cost exposure</h2></div></div><div className="table"><table><thead><tr><th>Sector</th><th>Projects</th><th>Average risk</th><th>Cost forecast</th><th>Portfolio budget</th></tr></thead><tbody>{bench.map(x=><tr key={x.sector}><td><b>{x.sector}</b></td><td>{x.projects}</td><td>{x.avg_risk}/100</td><td>{x.avg_cost_overrun}%</td><td>₹{fmt(x.budget)} Cr</td></tr>)}</tbody></table></div></div></section>}
 {view==='copilot'&&<section className="copilot-page"><div className="panel"><p className="eyebrow">PROJECT INTELLIGENCE ASSISTANT</p><h2>What needs attention?</h2><p className="subtitle">Choose a high-risk project and generate a recommended recovery brief.</p><div className="copilot-list">{ranking.slice(0,6).map(p=><button key={p.project_id} onClick={()=>ask(p.project_id)}><span><b>{p.project_name}</b><small>{p.project_id} · Risk {p.risk_score}/100</small></span><ChevronRight size={17}/></button>)}</div>{answer&&<div className="assistant-answer"><BrainCircuit size={19}/><div><b>PAIMANA AI recommendation</b><p>{answer}</p></div></div>}</div></section>}
 </main>{detail&&<Detail data={detail} onClose={()=>setDetail()} onAsk={()=>ask(detail.project.project_id)}/>}</div>
}
function AlertStream({alerts}){return <div className="panel alerts"><div className="head"><div><p className="eyebrow">EARLY WARNING</p><h2>Live alert stream</h2></div><AlertTriangle className="red"/></div>{alerts.slice(0,5).map((a,i)=><div className="alert" key={i}><i className={a.severity==='Critical'?'critical':''}/><div><b>{a.project_id}</b><p>{a.message}</p></div></div>)}</div>}
function BenchmarkChart({bench}){return <div className="panel wide"><div className="head"><div><p className="eyebrow">COMPARATIVE ANALYTICS</p><h2>Sector risk benchmark</h2></div></div><ResponsiveContainer width="100%" height={250}><BarChart data={bench}><XAxis dataKey="sector" tick={{fontSize:10}} interval={0}/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="avg_risk" radius={[7,7,0,0]}>{bench.map((x,i)=><Cell key={i} fill={x.avg_risk>58?'#f43f5e':'#0d9488'}/>)}</Bar></BarChart></ResponsiveContainer></div>}
function ModelCard(){return <div className="panel model"><p className="eyebrow">MODEL HEALTH</p><h2>Decision-ready signals</h2><div className="ring">84<small>%</small></div><p>Portfolio coverage based on current reporting fields.</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
